spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:ppshop}?serverTimezone=UTC
    username: ${RDS_USERNAME:ppshop}
    password: ${RDS_PASSWORD:chenxiao}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
logging:
  file:
    name: logs/app.log
